config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root "homes#index"
  resources :referrals, only: [:new, :create] do
    member do
      get :resend_referral
    end
  end
  resources :homes, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/referral.rb
class Referral < ApplicationRecord

  belongs_to :user

  enum status: { pending: 0, accepted: 1}

  validates :email, uniqueness: { scope: :user_id }, presence: true
  validates :uuid, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :referral, class_name: 'User', foreign_key: 'referral_id', optional: true
  has_many :referrals, dependent: :destroy

  enum role: { direct: 0, admin: 1, referral: 2 }

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseField
  include Pundit::Authorization

  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError do
    redirect_to root_path, alert: 'Only admins have access to this page'
  end
end

app/controllers/concerns/devise_field.rb
module DeviseField
  extend ActiveSupport::Concern

  included do
    before_action :configured_permitted_parameters, if: :devise_controller?
  end
  def configured_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :role, :referral_uuid])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  before_action :set_referral, only: [:resend_referral]
  before_action :verify_email_already_present?, only: [:create]

  def new
    authorize Referral
  end

  def create
    authorize Referral

    @referral = policy_scope(Referral).new(referral_params)
    respond_to do |format|
      if !verify_email_already_present? && @referral.save
        send_referral_invitation(@referral.email, @referral.uuid, @referral.user.first_name)
        flash[:notice] = 'Referral was created successfully'
        flash.keep(:notice)
        format.html { redirect_to root_path }
        format.json { render json: @referral, status: :ok }
      else
        format.html { redirect_to root_path, alert: @referral.errors.full_messages.to_sentence }
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  def resend_referral
    authorize @referral

    respond_to do |format|
      if @referral.resend_count <= 4 && @referral.update(resend_count: (@referral.resend_count + 1))
        send_referral_invitation(@referral.email, @referral.uuid, @referral.user.first_name)
        flash[:notice] = 'Referral was Resend successfully'
        flash.keep(:notice)
        format.html { redirect_to root_path }
        format.json { render json: @referral, status: :ok }
      else
        format.html { redirect_to root_path, alert: @referral.errors.full_messages.to_sentence }
        format.json { render json: @referral.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_referral
      @referral = Referral.find(params[:id])
    end

    def referral_params
      params.require(:referral).permit(:email).with_defaults(user: current_user, uuid: SecureRandom.uuid)
    end

    def send_referral_invitation(email, uuid, first_name)
      ReferralServices::SendReferralEmail.new(email, uuid, first_name).process
    end

    def verify_email_already_present?
      User.find_by(email: params[:referral][:email]).present?
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :get_referral_id, only: [:create]
  after_action :update_role_referral_id, only: [:create]

  private

    def update_role_referral_id
      if get_referral_id.present?
        current_user.update(role: :referral, referral_id: @referral.user_id)
        @referral.update(status: :accepted)
      end
    end

    def get_referral_id
      @referral = Referral.find_by(uuid: params["user"]["uuid"]) if params["user"]["uuid"].present?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_errors(object, field_name)
    if object.errors.any?
      if !object.errors.messages[field_name].blank?
        object.errors.messages[field_name].join(", ")
      end
    end
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/homes/index.html.erb
<%= render "referrals/home" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DsAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="mt-10 mx-40">
      <%= render "shared/navbar" %>
      <p class="notice mt-10 font-bold text-green-600 text-center"><%= notice %></p>
      <p class="alert mt-10 font-bold text-orange-600 text-center"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/referrals/_form.html.erb
<div class="flex min-h-full flex-col justify-center px-6">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Create New Referral</h2>
  </div>

  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <%= form_with scope: "referral", model: @referral, url: referrals_path, method: :post, local: true do |f| %>

      <div class="field mt-2">
        <%= f.label :email, class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>

      <div class="actions mt-4">
        <%= f.submit "Send Invite", class: "flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      </div>
    <% end %>

    <p class="mt-2 text-center text-lg text-gray-500">
      <%= link_to "Back", :back, class: "font-semibold leading-6 text-indigo-600 hover:text-indigo-500" %>
    </p>
  </div>
</div>

app/views/referrals/_home.html.erb
<% if policy(Referral).can_access? %>
  <%= render "referrals/referral_table" %>
<% else %>
  <%= render "referrals/user_details" %>
<% end %>

app/views/referrals/_referral_table.html.erb
<div class="px-48">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Referred Users</h1>
      <p class="mt-2 text-sm text-gray-700">List</p>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <%= button_to "Invite New User", new_referral_path, method: :get, class: "block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
    </div>
    <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Email</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Resend Count (Max limit 5)</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                <span class="sr-only">Resend Invite</span>
              </th>
            </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
            <% current_user.referrals.each do |referral| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= referral.email %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= referral.status %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= referral.resend_count %></td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <%= link_to "Resend Invite", resend_referral_referral_path(referral), class: "text-indigo-600 hover:text-indigo-900"  %>
                </td>
              </tr>
            <% end  %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/referrals/_user_details.html.erb
<div class="box-border h-100 w-100 p-4 border-4 justify-center mx-96">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Users Details </h1>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
          <tr>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Fields</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Details</th>
          </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
          <tr>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-5">First Name</td>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= current_user.first_name %></td>
          </tr>
          <tr>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-5">Last Name</td>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= current_user.last_name %></td>
          </tr>
          <tr>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-5">Email</td>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= current_user.email %></td>
          </tr>
          <% if current_user.referral? %>
            <tr>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-5">Referred by</td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= current_user.referral.first_name %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/referrals/new.html.erb
<%= render "form" %>

app/views/shared/_navbar.html.erb
<nav class="bg-slate-100 rounded-md">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <div class="text-xl font-bold text-indigo-600">
            <%= link_to "DS-Assignment", root_path %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <div class="relative ml-3">
          <div>
            <% if user_signed_in? %>
              <%= link_to "Edit Profile |", edit_user_registration_path, class: "text-indigo-600 font-bold" %>
              <%= link_to "Sign Out", destroy_user_session_path, class: "text-indigo-600 font-bold" %>
            <% else %>
              <%= link_to "Sign Up |", new_user_registration_path, class: "text-indigo-600 font-bold" %>
              <%= link_to "Sign In", user_session_path, class: "text-indigo-600 font-bold" %>
            <% end  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>